# Generated by Django 3.0.2 on 2020-01-29 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('is_valid', models.BooleanField(default=False)),
                ('bank_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_fk', to='bank.Bank')),
                ('client_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_fk', to='client.Client')),
                ('destination_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_fk', to='client.Client')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
            },
        ),
    ]
